In [1]:
import sys

In [2]:
sys.version

'3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]'

### NUMPY

In [3]:
import numpy as np

In [4]:
np.__version__

'1.24.2'

In [5]:
my_list =[0,1,2,3,4,5]

In [6]:
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

In [8]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [15]:
np.arange(10,30,30,3)

TypeError: Cannot interpret '3' as a data type

In [17]:
np.arange(20,8) #it  generate empty array 

array([], dtype=int32)

In [18]:
np.arange(-20,8) # always 1st arg < 2nd arg 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
nd= np.zeros((5,5),dtype= int)
nd

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [24]:
nd1= np.ones((5,5),dtype=int)

In [25]:
nd1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
np.random.rand(3)

array([0.9986531 , 0.75954063, 0.47436141])

In [27]:
np.random.rand(3)

array([0.61289203, 0.62628854, 0.94091129])

In [28]:
np.random.rand(2,3)

array([[0.75255001, 0.30950801, 0.23396592],
       [0.5085997 , 0.36264126, 0.77984209]])

In [29]:
np.random.rand(2,3)# gives some random values

array([[0.39083042, 0.23265058, 0.54095641],
       [0.67588557, 0.08917304, 0.56800688]])

In [30]:
np.random.randint(3) #gives some random variables with in the range

0

In [31]:
np.random.randint(3,10)

6

In [32]:
np.random.randint(2,8,5)

array([2, 7, 6, 2, 4])

In [33]:
np.random.randint(-20,13,6)

array([-10, -18, -20,   5, -10,  -2])

In [34]:
np.random.randint(1,50,(4,6))

array([[21, 37, 23, 25, 22, 10],
       [ 7, 16,  8, 12, 23, 33],
       [27, 28, 41,  6, 15, 35],
       [20, 23,  5, 12, 17,  2]])

In [35]:
m= np.random.randint(9,50,(7,8))
m

array([[25, 36, 21, 43, 47, 33, 27, 49],
       [48, 47, 33, 36, 29, 30, 29, 37],
       [17, 48,  9, 22, 41, 23, 33, 20],
       [ 9, 29, 15, 16, 21, 20, 36, 24],
       [49, 22, 14, 15, 44, 21, 36, 48],
       [45, 33, 15, 29, 35, 10, 22, 11],
       [13, 31, 14, 27, 38, 36, 40, 29]])

In [36]:
arr

array([0, 1, 2, 3, 4, 5])

In [37]:
arr.reshape(2,3) #reshapes the arr into 2 rows and 3 colms values having 6 elements in arr 

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

### Slicing in matrix

In [39]:
b= np.random.randint(3,28,(5,4))
b

array([[ 7, 24, 14, 24],
       [23, 16, 17, 23],
       [26, 23, 18, 18],
       [14,  4, 10, 11],
       [22,  5,  8, 18]])

In [40]:
b[:]

array([[ 7, 24, 14, 24],
       [23, 16, 17, 23],
       [26, 23, 18, 18],
       [14,  4, 10, 11],
       [22,  5,  8, 18]])

In [41]:
b[1:4]

array([[23, 16, 17, 23],
       [26, 23, 18, 18],
       [14,  4, 10, 11]])

In [42]:
b

array([[ 7, 24, 14, 24],
       [23, 16, 17, 23],
       [26, 23, 18, 18],
       [14,  4, 10, 11],
       [22,  5,  8, 18]])

In [43]:
b[2,2]

18

In [46]:
b[2:4]

array([[26, 23, 18, 18],
       [14,  4, 10, 11]])

In [55]:
b[-3:-2]

array([[26, 23, 18, 18]])

### Operations

In [56]:
a=np.random.randint(10,20,10)
a

array([18, 13, 10, 13, 18, 16, 10, 15, 16, 12])

In [57]:
arr

array([0, 1, 2, 3, 4, 5])

In [58]:
arr2=np.random.randint(0,100,(9,9))
arr2

array([[70, 81, 36, 91, 66,  6, 99, 70, 33],
       [21, 89, 57, 63, 57, 18, 36,  8, 94],
       [10, 90,  6, 11, 48, 15, 37,  5, 55],
       [74, 32, 12, 49, 83, 14, 17, 10, 64],
       [ 9,  3, 21, 26, 44, 24, 23, 86, 44],
       [79,  7, 40, 45, 32, 57,  0, 28, 13],
       [ 0, 27, 39, 92, 77, 11, 90, 29, 16],
       [21, 58, 24, 32, 29,  5, 13,  9,  3],
       [69, 14, 32, 67, 45, 42, 58, 53, 87]])

In [60]:
arr2[0:3]

array([[70, 81, 36, 91, 66,  6, 99, 70, 33],
       [21, 89, 57, 63, 57, 18, 36,  8, 94],
       [10, 90,  6, 11, 48, 15, 37,  5, 55]])

In [63]:
arr2[2,3]

11

In [64]:
arr[::-1]

array([5, 4, 3, 2, 1, 0])

In [65]:
arr2[::-1]

array([[69, 14, 32, 67, 45, 42, 58, 53, 87],
       [21, 58, 24, 32, 29,  5, 13,  9,  3],
       [ 0, 27, 39, 92, 77, 11, 90, 29, 16],
       [79,  7, 40, 45, 32, 57,  0, 28, 13],
       [ 9,  3, 21, 26, 44, 24, 23, 86, 44],
       [74, 32, 12, 49, 83, 14, 17, 10, 64],
       [10, 90,  6, 11, 48, 15, 37,  5, 55],
       [21, 89, 57, 63, 57, 18, 36,  8, 94],
       [70, 81, 36, 91, 66,  6, 99, 70, 33]])

In [66]:
arr2.max()

99

In [67]:
arr2.min()

0

In [68]:
arr.mean()

2.5

In [69]:
arr2.mean()

40.123456790123456

In [71]:
from numpy import *

In [73]:
median(arr)

2.5

In [74]:
arr

array([0, 1, 2, 3, 4, 5])

In [75]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [80]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
arr.reshape(2,3,order='F') 

array([[0, 2, 4],
       [1, 3, 5]])

In [82]:
arr.reshape(2,3,order='A') 

array([[0, 1, 2],
       [3, 4, 5]])

In [83]:
mat=np.arange(0,100).reshape(10,10)

In [84]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [85]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [87]:
mat[4,3]

43

In [88]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [91]:
mat[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [94]:
mat[6,:]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [95]:
mat[0:10:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [96]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [98]:
mat[3:7,4:6]

array([[34, 35],
       [44, 45],
       [54, 55],
       [64, 65]])

### Masking

In [99]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [100]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [101]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### OTP generation

In [106]:
import random
def generate_otp(length=4):
    digits='0123456'
    otp=''.join(random.choice(digits) for _ in range(length))
    return otp

otp_length= 4
otp= generate_otp(otp_length)
print(f'Your OTP is : {otp}')
    

Your OTP is : 6565


In [ ]:
np.ravel
np.vstack

In [107]:
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2])  # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [108]:
a2 = np.array([1, 2])
b2 = np.array([3, 4])
a=np.array([a2,b2])
a

array([[1, 2],
       [3, 4]])