In [1]:
 import numpy as np

In [2]:
np.__version__

'1.24.2'

### Creating an array

In [3]:
a1= np.array([1,2,3,4,5,6,7,8,9]) # 1D array 
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a2= np.array([[1,2,3],[4,5,6]]) #2D array
a3= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #3D array
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Data Type

In [6]:
np.array([1,2,3], dtype= float) # float dtype

array([1., 2., 3.])

In [7]:
np.array([2,3,4], dtype= bool) # boolean atype

array([ True,  True,  True])

In [8]:
np.array([2,3,4], dtype= complex) # complex dtype

array([2.+0.j, 3.+0.j, 4.+0.j])

In [9]:
# arange() - returns array values from 1 to 10
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,10,2) # return alternate numbers upto 9

array([1, 3, 5, 7, 9])

In [11]:
# reshape() - use to reshape the array

np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
# zeros()- create an array with zeros
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [14]:
# ones()- create an array with ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# random() - creates an array with random values

np.random.random((2,3))

array([[0.19517342, 0.69459678, 0.41261395],
       [0.00097452, 0.22299923, 0.38829329]])

In [16]:
np.random.randint(0,10,(3,2))

array([[3, 8],
       [2, 0],
       [2, 2]])

In [17]:
# linespace()- create an array with linear or equal distances b/w the values

np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [18]:
# identity()/eye() - creates an identity matrix or array

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(4,dtype= int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [20]:
# ndim - gives the dimention of the array

a1.ndim

1

In [21]:
a2.ndim

2

In [22]:
a3.ndim

3

In [23]:
# shape - gives the shppe of the array

a3.shape

(2, 2, 3)

In [24]:
a2.shape

(2, 3)

In [25]:
a1.shape

(9,)

In [26]:
#size - returns total no.of elements in array

a3.size

12

In [27]:
a2.size

6

In [28]:
# itemsize - returns the memory occupiedby array

a3.itemsize

4

In [29]:
a2.itemsize

4

In [30]:
a1.itemsize

4

In [31]:
# astype() - to change the type of the array

a= np.array([1.,2,3.6])
a

array([1. , 2. , 3.6])

In [32]:
a.astype(int)

array([1, 2, 3])

### Array operations

In [33]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a2+3

array([[4, 5, 6],
       [7, 8, 9]])

In [35]:
a2-1

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
a2*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [37]:
a2/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [38]:
a2**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [39]:
# relation operators

a2

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a2 > 3

array([[False, False, False],
       [ True,  True,  True]])

In [41]:
a2 < 3

array([[ True,  True, False],
       [False, False, False]])

In [42]:
a2 <= 3

array([[ True,  True,  True],
       [False, False, False]])

In [43]:
# Vector operations

a2

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
a4=np.array([[7,8,9],[10,11,12]])
a4

array([[ 7,  8,  9],
       [10, 11, 12]])

In [45]:
a2+a4

array([[ 8, 10, 12],
       [14, 16, 18]])

In [46]:
a2-a4

array([[-6, -6, -6],
       [-6, -6, -6]])

In [47]:
a2* a4

array([[ 7, 16, 27],
       [40, 55, 72]])

In [48]:
# array functions

np.max(a2)

6

In [49]:
np.min(a2)

1

In [50]:
np.max(a4)

12

In [51]:
np.sum(a2)

21

In [52]:
np.prod(a2)

720

In [53]:
np.max(a4,axis =1) # maximum value in each row(axis-0 represents column and axis-1 represents row)

array([ 9, 12])

In [54]:
np.prod(a2,axis=1) # product of each row

array([  6, 120])

In [55]:
np.sum(a2,axis = 1) # sum of each row

array([ 6, 15])

In [56]:
np.sum(a2,axis=0) # sum of each column

array([5, 7, 9])

In [57]:
# Statistical related functions(mean,median,sd,etcc)

a2

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a4

array([[ 7,  8,  9],
       [10, 11, 12]])

In [59]:
np.mean(a4)

9.5

In [60]:
np.mean(a4, dtype= int,axis=1) # mean of each row

array([ 8, 11])

In [61]:
np.std(a4)

1.707825127659933

In [62]:
np.std(a4, axis= 0) # standard deviation of each column

array([1.5, 1.5, 1.5])

In [63]:
s1= np.array([[2,5,7,8],[3,5,1,9],[11,9,12,7]])
s1

array([[ 2,  5,  7,  8],
       [ 3,  5,  1,  9],
       [11,  9, 12,  7]])

In [64]:
np.std(s1, axis= 0) # standard deviation of each column

array([4.02768199, 1.88561808, 4.49691252, 0.81649658])

In [65]:
 np.var(s1)

11.076388888888888

In [66]:
np.var(s1,axis=1 ) # variance of each row

array([5.25  , 8.75  , 3.6875])

In [67]:
a2*a2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [68]:
a2**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [69]:
s2= np.arange(9,18).reshape((3,3))
s3= np.arange(9).reshape((3,3))

In [70]:
s2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [71]:
s3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
s2*s3

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [73]:
np.dot(s2,s3) # dot product of s2, s3(matrix multiplication)

array([[ 96, 126, 156],
       [123, 162, 201],
       [150, 198, 246]])

In [74]:
np.exp(s2)

array([[8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07]])

In [75]:
s4= np.random.randint(0,10,(3,3))

In [76]:
s4

array([[3, 3, 4],
       [5, 1, 9],
       [8, 4, 3]])

In [77]:
# round() - gives the round of value

s5= np.array([1.2,1.3,2.4,4.5])
round_arr= np.round(s5)
print(f'without round() ={s5}')
print(f'with round() = {round_arr}')

without round() =[1.2 1.3 2.4 4.5]
with round() = [1. 1. 2. 4.]


In [78]:
# floor() - gives the floor value 

floor_ar=np.floor(s5)
print(f'using floor() = {floor_ar}')

using floor() = [1. 1. 2. 4.]


In [79]:
# ceil() - gives the ceiling value

ceil_arr = np.ceil(s5)
print(f'uing ceil() = {ceil_arr}')

uing ceil() = [2. 2. 3. 5.]


In [80]:
np.ceil(np.random.random((3,3))*100)

array([[ 8., 85., 91.],
       [60., 10., 75.],
       [91., 34., 77.]])

###  Indexing and slicing in numpy

In [81]:
# indexing a 1D array

m1= np.random.randint(0,11,6)
m1

array([ 5, 10,  3,  1,  2,  2])

In [82]:
# indexing

m1[1]

10

In [83]:
m1[-2]

2

In [84]:
# slicing 

m1[:]

array([ 5, 10,  3,  1,  2,  2])

In [85]:
m1[:2]

array([ 5, 10])

In [86]:
m1[2:5]

array([3, 1, 2])

In [87]:
m1[::-1]

array([ 2,  2,  1,  3, 10,  5])

In [88]:
# indexing a 2D array

m2= np.random.randint(0,11,(2,3))
m2

array([[ 3,  1, 10],
       [ 6, 10,  8]])

In [89]:
m2.ndim

2

In [90]:
# indexing

m2[1,1]

10

In [91]:
m2[0,0]

3

In [92]:
m2[1,]

array([ 6, 10,  8])

In [93]:
# Sclicing 

m2[:]

array([[ 3,  1, 10],
       [ 6, 10,  8]])

In [94]:
m2[0,:]

array([ 3,  1, 10])

In [95]:
m2[:,1] # prints the 2nd coloum values 

array([ 1, 10])

In [96]:
m2[0:2] # to print the rows

array([[ 3,  1, 10],
       [ 6, 10,  8]])

In [97]:
m2[0:2,1:]  # to print the columns

array([[ 1, 10],
       [10,  8]])

In [98]:
m2[1,2]

8

In [99]:
m3= np.random.randint(0,16,(3,3))

In [100]:
m3

array([[ 5,  3,  4],
       [ 8,  1, 10],
       [13, 14,  0]])

In [101]:
m3[2,1]

14

In [102]:
m3[::-1] # to print the reverse of the array

array([[13, 14,  0],
       [ 8,  1, 10],
       [ 5,  3,  4]])

In [103]:
m3[::2] # to print the every 2nd row of the array

array([[ 5,  3,  4],
       [13, 14,  0]])

In [104]:
m3[:,::2] # to print the every 2nd coloum of the array

array([[ 5,  4],
       [ 8, 10],
       [13,  0]])

In [105]:
# indexing and sclicing in 3D

m4= np.random.randint(0,16,(2,2,2))
m4

array([[[ 4, 15],
        [ 3,  2]],

       [[10,  9],
        [ 8,  4]]])

In [106]:
# indexing in 3d array

m4[1,1,1]

4

In [107]:
m4[0,1,]

array([3, 2])

In [108]:
m4[1,0,]

array([10,  9])

In [109]:
# Sclicing in 3d

m5= np.random.randint(0,16,(3,3,3))
m5

array([[[11,  3,  8],
        [ 6,  9, 14],
        [ 7, 11,  5]],

       [[13, 11,  2],
        [ 7,  5,  8],
        [13, 13,  7]],

       [[ 6,  9,  8],
        [15,  0, 15],
        [14, 14, 10]]])

In [110]:
m5[0]

array([[11,  3,  8],
       [ 6,  9, 14],
       [ 7, 11,  5]])

In [111]:
m5[1]

array([[13, 11,  2],
       [ 7,  5,  8],
       [13, 13,  7]])

In [112]:
m5[2]

array([[ 6,  9,  8],
       [15,  0, 15],
       [14, 14, 10]])

In [113]:
m5[1:]

array([[[13, 11,  2],
        [ 7,  5,  8],
        [13, 13,  7]],

       [[ 6,  9,  8],
        [15,  0, 15],
        [14, 14, 10]]])

In [114]:
m5[:2]

array([[[11,  3,  8],
        [ 6,  9, 14],
        [ 7, 11,  5]],

       [[13, 11,  2],
        [ 7,  5,  8],
        [13, 13,  7]]])

In [115]:
m5[::2] # Along the first axis, (::2) selects every second element. This means it will select the subarrays at indices 0 and 2 

array([[[11,  3,  8],
        [ 6,  9, 14],
        [ 7, 11,  5]],

       [[ 6,  9,  8],
        [15,  0, 15],
        [14, 14, 10]]])

In [116]:
m5[2,1,:] 

array([15,  0, 15])

In [117]:
m5[2,:,1]

array([ 9,  0, 14])

In [118]:
m5[:,1,2]

array([14,  8, 15])

In [119]:
m5[::2,0,::2]

array([[11,  8],
       [ 6,  8]])

In [120]:
m5 # m5[1,1,1]- first row , first coloum, first attribute

array([[[11,  3,  8],
        [ 6,  9, 14],
        [ 7, 11,  5]],

       [[13, 11,  2],
        [ 7,  5,  8],
        [13, 13,  7]],

       [[ 6,  9,  8],
        [15,  0, 15],
        [14, 14, 10]]])

In [121]:
m5[:,::2,:]

array([[[11,  3,  8],
        [ 7, 11,  5]],

       [[13, 11,  2],
        [13, 13,  7]],

       [[ 6,  9,  8],
        [14, 14, 10]]])

### Iterating or loops

In [122]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
m4

array([[[ 4, 15],
        [ 3,  2]],

       [[10,  9],
        [ 8,  4]]])

In [125]:
for i in a1:
    print(i)

1
2
3
4
5
6
7
8
9


In [126]:
for i in a2:
    print(i)

[1 2 3]
[4 5 6]


In [127]:
for i in a3:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [128]:
for i in np.nditer(a3):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


### Reshaping

In [129]:
m3

array([[ 5,  3,  4],
       [ 8,  1, 10],
       [13, 14,  0]])

In [130]:
# Transpose- use np.transpose() or .T

np.transpose(m3)

array([[ 5,  8, 13],
       [ 3,  1, 14],
       [ 4, 10,  0]])

In [131]:
m3.T

array([[ 5,  8, 13],
       [ 3,  1, 14],
       [ 4, 10,  0]])

In [132]:
# ravel - used to convert nD array into 1D array

m3.ravel()

array([ 5,  3,  4,  8,  1, 10, 13, 14,  0])

In [133]:
m4

array([[[ 4, 15],
        [ 3,  2]],

       [[10,  9],
        [ 8,  4]]])

In [134]:
m4.ravel()

array([ 4, 15,  3,  2, 10,  9,  8,  4])

In [135]:
# stacking

x1= np.random.randint(0,16,(4,3))
x2= np.random.randint(0,16,(4,3))

In [136]:
x1

array([[13,  3,  4],
       [ 7, 11,  6],
       [ 0,  7,  7],
       [ 2,  6,  6]])

In [137]:
x2

array([[ 5,  9, 11],
       [ 0,  0, 15],
       [13, 13, 11],
       [ 4,  4,  3]])

In [138]:
np.hstack((x1,x2)) # use to stack two arrays horizontally

array([[13,  3,  4,  5,  9, 11],
       [ 7, 11,  6,  0,  0, 15],
       [ 0,  7,  7, 13, 13, 11],
       [ 2,  6,  6,  4,  4,  3]])

In [139]:
np.hstack((x2,x1))

array([[ 5,  9, 11, 13,  3,  4],
       [ 0,  0, 15,  7, 11,  6],
       [13, 13, 11,  0,  7,  7],
       [ 4,  4,  3,  2,  6,  6]])

In [140]:
np.vstack((x1,x2)) # used to stack two arrays vertically

array([[13,  3,  4],
       [ 7, 11,  6],
       [ 0,  7,  7],
       [ 2,  6,  6],
       [ 5,  9, 11],
       [ 0,  0, 15],
       [13, 13, 11],
       [ 4,  4,  3]])

In [141]:
np.vstack((x2,x1))

array([[ 5,  9, 11],
       [ 0,  0, 15],
       [13, 13, 11],
       [ 4,  4,  3],
       [13,  3,  4],
       [ 7, 11,  6],
       [ 0,  7,  7],
       [ 2,  6,  6]])

In [142]:
# splitting

x3= np.random.randint(0,16,(3,4))

In [143]:
x3

array([[ 7, 13,  4, 10],
       [ 4,  3,  0,  3],
       [ 8,  3,  8,  9]])

In [144]:
np.hsplit(x3,2) # use hsplit the split the values horizontally

[array([[ 7, 13],
        [ 4,  3],
        [ 8,  3]]),
 array([[ 4, 10],
        [ 0,  3],
        [ 8,  9]])]

In [145]:
np.hsplit(x3,4)

[array([[7],
        [4],
        [8]]),
 array([[13],
        [ 3],
        [ 3]]),
 array([[4],
        [0],
        [8]]),
 array([[10],
        [ 3],
        [ 9]])]

In [146]:
np.vsplit(x3,3) # spliting the value vertically

[array([[ 7, 13,  4, 10]]), array([[4, 3, 0, 3]]), array([[8, 3, 8, 9]])]

In [147]:
x3= np.expand_dims(x3,axis =1)


In [148]:
x3

array([[[ 7, 13,  4, 10]],

       [[ 4,  3,  0,  3]],

       [[ 8,  3,  8,  9]]])

In [149]:
x3.ndim

3

In [150]:
m3

array([[ 5,  3,  4],
       [ 8,  1, 10],
       [13, 14,  0]])

In [151]:
m3[[0,2],1]

array([ 3, 14])

In [152]:
m4

array([[[ 4, 15],
        [ 3,  2]],

       [[10,  9],
        [ 8,  4]]])

In [153]:
m4[1,[0,1],1]

array([9, 4])

In [154]:
# boolen indexing

m3 > 4

array([[ True, False, False],
       [ True, False,  True],
       [ True,  True, False]])

In [155]:
# to get the element greater than 4 use flitering

m3[m3>4]

array([ 5,  8, 10, 13, 14])

In [156]:
# sorting 

a= np.random.randint(0,50,15)
a

array([ 0, 37, 32, 34,  1,  2, 37, 15,  1, 24,  6,  6, 37, 19, 31])

In [157]:
b= np.random.randint(0,50,16).reshape(4,4)
b

array([[40,  6,  3, 13],
       [40, 13,  2, 47],
       [12, 37, 18, 29],
       [ 2,  8,  2, 49]])

In [158]:
np.sort(a)

array([ 0,  1,  1,  2,  6,  6, 15, 19, 24, 31, 32, 34, 37, 37, 37])

In [159]:
np.sort(b) # sort by rows

array([[ 3,  6, 13, 40],
       [ 2, 13, 40, 47],
       [12, 18, 29, 37],
       [ 2,  2,  8, 49]])

In [160]:
# append

np.append(a,50)

array([ 0, 37, 32, 34,  1,  2, 37, 15,  1, 24,  6,  6, 37, 19, 31, 50])

In [161]:
c=np.random.randint(0,20,16).reshape(4,4)
c

array([[ 0, 16,  0, 12],
       [ 9,  4,  4, 14],
       [ 6, 16, 17,  9],
       [14,  8,  6,  5]])

In [162]:
np.concatenate((b,c),axis=0)

array([[40,  6,  3, 13],
       [40, 13,  2, 47],
       [12, 37, 18, 29],
       [ 2,  8,  2, 49],
       [ 0, 16,  0, 12],
       [ 9,  4,  4, 14],
       [ 6, 16, 17,  9],
       [14,  8,  6,  5]])

In [163]:
np.concatenate((b,c),axis=1)

array([[40,  6,  3, 13,  0, 16,  0, 12],
       [40, 13,  2, 47,  9,  4,  4, 14],
       [12, 37, 18, 29,  6, 16, 17,  9],
       [ 2,  8,  2, 49, 14,  8,  6,  5]])

In [164]:

np.unique(a)

array([ 0,  1,  2,  6, 15, 19, 24, 31, 32, 34, 37])

In [165]:
np.unique(c)

array([ 0,  4,  5,  6,  8,  9, 12, 14, 16, 17])

In [166]:
# where()

np.where(a>12,a,0)

array([ 0, 37, 32, 34,  0,  0, 37, 15,  0, 24,  0,  0, 37, 19, 31])

In [167]:
a

array([ 0, 37, 32, 34,  1,  2, 37, 15,  1, 24,  6,  6, 37, 19, 31])

In [168]:
np.where(a>12,0,1)

array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0])

In [169]:
# np.argmax - is used to written the incx no. of the maximum element in the array

a = np.random.randint(0,50,12)

In [170]:
a

array([ 1, 31, 34,  8, 29, 17, 35, 18, 16, 43, 26, 17])

In [171]:
np.argmax(a)

9

In [172]:
a[7]

18

In [173]:
# cumsum 

np.cumsum(a)

array([  1,  32,  66,  74, 103, 120, 155, 173, 189, 232, 258, 275])

In [174]:
b= np.random.randint(0,25,16).reshape(4,4)
b

array([[19,  4, 22, 19],
       [ 8,  7,  5, 20],
       [ 7, 23, 20,  7],
       [10, 13, 13,  8]])

In [175]:
np.cumsum(b)

array([ 19,  23,  45,  64,  72,  79,  84, 104, 111, 134, 154, 161, 171,
       184, 197, 205])

In [176]:
np.cumsum(b,axis=1)

array([[19, 23, 45, 64],
       [ 8, 15, 20, 40],
       [ 7, 30, 50, 57],
       [10, 23, 36, 44]])

In [177]:
np.cumsum(b,axis=0)

array([[19,  4, 22, 19],
       [27, 11, 27, 39],
       [34, 34, 47, 46],
       [44, 47, 60, 54]])

In [178]:
np.cumprod(a)

array([          1,          31,        1054,        8432,      244528,
           4156976,   145494160, -1676072416, -1047354880, -2086586880,
        1583315968,  1146567680])

In [179]:
np.cumprod(b,axis=0)

array([[   19,     4,    22,    19],
       [  152,    28,   110,   380],
       [ 1064,   644,  2200,  2660],
       [10640,  8372, 28600, 21280]])

In [180]:
np.cumprod(b,axis=1)

array([[   19,    76,  1672, 31768],
       [    8,    56,   280,  5600],
       [    7,   161,  3220, 22540],
       [   10,   130,  1690, 13520]])

In [181]:
# np.histogram - used to represent the frequency of data distribution 

np.histogram(a, bins= [0,10,20,30,40,50])

(array([2, 4, 2, 3, 1], dtype=int64), array([ 0, 10, 20, 30, 40, 50]))

In [182]:
# np.corrcoef - checks how two variables are corelated to each other

height =np.array([151,161,165,157,173,167])
weight = np.array([51,56,57,52,65,56])

In [183]:
np.corrcoef(height,weight)

array([[1.        , 0.91827531],
       [0.91827531, 1.        ]])

In [184]:
a

array([ 1, 31, 34,  8, 29, 17, 35, 18, 16, 43, 26, 17])

In [185]:
f= np.random.randint(0,50,12)

In [186]:
# np.isin - use to check different elements in two variables

np.isin(a,f)

array([ True, False, False, False,  True, False, False, False, False,
       False, False, False])

In [187]:
np.isin(f,a)

array([False, False, False, False, False,  True, False, False, False,
       False, False,  True])

In [188]:
a[np.isin(a,f)]

array([ 1, 29])

In [189]:
a

array([ 1, 31, 34,  8, 29, 17, 35, 18, 16, 43, 26, 17])

In [190]:
# np.flip()- used to reverses the array 
np.flip(a)

array([17, 26, 43, 16, 18, 35, 17, 29,  8, 34, 31,  1])

In [191]:
print(b)
print('reverse of b is \n',np.flip(b))

[[19  4 22 19]
 [ 8  7  5 20]
 [ 7 23 20  7]
 [10 13 13  8]]
reverse of b is 
 [[ 8 13 13 10]
 [ 7 20 23  7]
 [20  5  7  8]
 [19 22  4 19]]


In [192]:
# np.put() - is used to repalce an array element with give values

np.put(a,[1,2],[10,20])
a

array([ 1, 10, 20,  8, 29, 17, 35, 18, 16, 43, 26, 17])

In [193]:
# np.delete() - used to delete a value from the array by index

np.delete(a,0)

array([10, 20,  8, 29, 17, 35, 18, 16, 43, 26, 17])

In [194]:
a

array([ 1, 10, 20,  8, 29, 17, 35, 18, 16, 43, 26, 17])

In [195]:
#np.clip()- use to limits the values in the array 

np.clip(a,a_min=5,a_max=45)

array([ 5, 10, 20,  8, 29, 17, 35, 18, 16, 43, 26, 17])

In [196]:
# np.swapaxes - is used to inter change the axes  in the array

d= np.random.randint(0,15,6).reshape(2,3)
d

array([[12,  8,  7],
       [ 7,  7,  5]])

In [197]:
np.swapaxes(d,0,1)

array([[12,  7],
       [ 8,  7],
       [ 7,  5]])